# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fq < Formula
  desc "jq for binary formats"
  homepage "https://github.com/wader/fq"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wader/fq/releases/download/v0.10.0/fq_0.10.0_macos_arm64.zip"
      sha256 "f5445765923fc628673b4ff835962829b72fb5ea0962d6804f3479b894d15ea7"

      def install
        bin.install "fq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.10.0/fq_0.10.0_macos_amd64.zip"
      sha256 "5215e285fb60ddbdcf74278564b381a3948b89daca1acc091f3e99ca98215f2b"

      def install
        bin.install "fq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.10.0/fq_0.10.0_linux_amd64.tar.gz"
      sha256 "f02cec03ed73bb1263650311f62ecb505dc4382634aab46d063b54a443fd3b72"

      def install
        bin.install "fq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wader/fq/releases/download/v0.10.0/fq_0.10.0_linux_arm64.tar.gz"
      sha256 "317c98f4abb276386fa5ff501e578fcdf24b161c13fa40e1a849c2abc18c855a"

      def install
        bin.install "fq"
      end
    end
  end

  test do
    system "#{bin}/fq -v"
  end
end
