# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fq < Formula
  desc "jq for binary formats"
  homepage "https://github.com/wader/fq"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.6.0/fq_0.6.0_macos_amd64.zip"
      sha256 "63dae9853fedc27b3f6c8ef4863be6b4ae0ac9ee060ec7e21f9eceb26cf188b3"

      def install
        bin.install "fq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wader/fq/releases/download/v0.6.0/fq_0.6.0_macos_arm64.zip"
      sha256 "b1521817ab30cc2f41e959c1945d26845043fd98d69eb9e793d7643046a6d104"

      def install
        bin.install "fq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wader/fq/releases/download/v0.6.0/fq_0.6.0_linux_arm64.tar.gz"
      sha256 "31df342649d1e207ac7aa5775fdcdc41e9f11dd70ed500fab4bc28324500f128"

      def install
        bin.install "fq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.6.0/fq_0.6.0_linux_amd64.tar.gz"
      sha256 "74f204c91b876672f6b24e2445488651dcb3d869b414d27d9f1ffe38a361f466"

      def install
        bin.install "fq"
      end
    end
  end

  test do
    system "#{bin}/fq -v"
  end
end
