# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fq < Formula
  desc "jq for binaries"
  homepage "https://github.com/wader/fq"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.0.2/fq_0.0.2_macos_amd64.tar.gz"
      sha256 "2e52b8960f1ad01b3ecfcc491540036b32cbfc0f1c56998f90bd97f6a0b65e14"
    end
    if Hardware::CPU.arm?
      url "https://github.com/wader/fq/releases/download/v0.0.2/fq_0.0.2_macos_arm64.tar.gz"
      sha256 "8a026728802b6052c2e7d5c5c989979f5b5b88b62bce25ee4eed6d19d26d9e55"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wader/fq/releases/download/v0.0.2/fq_0.0.2_linux_amd64.tar.gz"
      sha256 "5ba3fc27f867306f0cc481f0a5c923e8d1adf6d037cc48bad3a9aac1b672040a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wader/fq/releases/download/v0.0.2/fq_0.0.2_linux_arm64.tar.gz"
      sha256 "741798fce22fd1c5f7135589c1a795ccb3f95544c09a6e332e06abe7e148e77a"
    end
  end

  def install
    bin.install "fq"
  end

  test do
    system "#{bin}/fq -v"
  end
end
