# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JqLsp < Formula
  desc "jq language server"
  homepage "https://github.com/wader/jq-lsp"
  version "0.1.14"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/wader/jq-lsp/releases/download/v0.1.14/jq-lsp_0.1.14_macos_amd64.zip"
      sha256 "7de86266570f12c4c3ed96d3a23e3301639246b3fc6441b528ccb64e363901fa"

      def install
        bin.install "jq-lsp"
      end
    end
    on_arm do
      url "https://github.com/wader/jq-lsp/releases/download/v0.1.14/jq-lsp_0.1.14_macos_arm64.zip"
      sha256 "46d9551e3c338c74ca57b8490f9340d25b046156f72b8c4ccb441ef6e205cbc7"

      def install
        bin.install "jq-lsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wader/jq-lsp/releases/download/v0.1.14/jq-lsp_0.1.14_linux_amd64.tar.gz"
        sha256 "c087017b898061216a08e0913fb2c0f2a7b45f138cf9ed6f2e1842f4ca72180c"

        def install
          bin.install "jq-lsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wader/jq-lsp/releases/download/v0.1.14/jq-lsp_0.1.14_linux_arm64.tar.gz"
        sha256 "e8002b8a52599ea0a679b47016fa0c7ec9e0ba3968e08f66b541d524094c7730"

        def install
          bin.install "jq-lsp"
        end
      end
    end
  end

  test do
    system "#{bin}/jq-lsp --version"
  end
end
